import {colors} from './colors';

// import DeviceInfo from 'react-native-device-info';
export default {
  BUTTON_TYPE: {
    PRIMARY: 'primary',
    SECONDARY: 'secondary',
    TERTIARY: 'tertiary',
  },
  RISK_TYPE: {
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
  },
  DATE_FORMAT: "YYYY-MM-DD",
  EVENT_NAME: {
    FOOD_DIARY: {
      CLICKED_HEALTH_DIARY: "CLICKED_HEALTH_DIARY",
      USER_CLICKS_ON_INSIGHT: "USER_CLICKS_ON_INSIGHT",
      USER_CLICKS_ON_OPTION: "USER_CLICKS_ON_OPTION",
      USER_CLICKED_ON_EDIT_MEAL: "USER_CLICKED_ON_EDIT_MEAL",
      USER_CLICKED_ON_DELETE_MEAL: "USER_CLICKED_ON_DELETE_MEAL",
      USER_CLICKED_ADD_FOOD_DISH: "USER_CLICKED_ADD_FOOD_DISH",
      USER_SEARCHED_FOOD_DISH: "USER_SEARCHED_FOOD_DISH",
      USER_SELECTED_FOOD_DISH: "USER_SELECTED_FOOD_DISH",
      USER_ADDED_QUANTITY: "USER_ADDED_QUANTITY",
      USER_ADDED_MEASURE: "USER_ADDED_MEASURE",
      USER_LOGGED_MEAL: "USER_LOGGED_MEAL",
      USER_CHANGES_MONTH: "USER_CHANGES_MONTH",
      USER_CHANGES_DATE: "USER_CHANGES_DATE",
      EXPAND_CALENDAR: "EXPAND_CALENDAR"
    }
  }
};
