export default {
  MysteryBox: require('../assets/images/mysteryBox.png'),
  OnBoard1: require('../assets/images/onboard1.png'),
  OnBoard2: require('../assets/images/onBoard2.png'),
  OnBoard3: require('../assets/images/onBoard3.png'),
  MedicalIcon: require('../assets/images/medicalKit.png'),
  GroupIcon: require('../assets/images/group.png'),
  LifeStyleIcon: require('../assets/images/life.png'),
  HearRateIcon: require('../assets/images/heartRate.png'),
  Diet: require('../assets/images/healthyfood.png'),
  Exercies: require('../assets/images/weightlifting.png'),
  Like: require('../assets/images/like.png'),
  Save: require('../assets/images/save.png'),
  ProgressBar: require('../assets/images/progressBar.png'),
};
