# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def shared_pods
  # Pods for MyTatva
#  5.2.11
  pod 'WebEngage'
end

target 'MyTatva' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    use_react_native!
  platform :ios, '13.0'
  config = use_native_modules!
  shared_pods
  
  target 'MyTatvaTests' do
    inherit! :search_paths
    #pods for your unit tests
  end
  
  target 'MyTatvaUITests' do
  end
    
  pod 'AdvancedPageControl'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyJSON'
#  pod 'SimpleImageViewer'
  pod 'Siren'
  pod 'QorumLogs'
  pod 'Moya'
  pod 'SDWebImage', :modular_headers => true

  pod 'lottie-ios'
#  pod 'FittedSheets'
  #pod 'iOSDropDown'
  pod 'RangeSeekSlider'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'AWSS3'
  pod 'AWSCore'
  pod 'SkyFloatingLabelTextField'
#  pod 'PDFReader'

  #pod 'FBSDKLoginKit'
  #pod 'FBSDKCoreKit'
  #pod 'FBSDKShareKit'
  #pod 'GoogleSignIn'
  #pod 'libPhoneNumber-iOS', '~> 0.9.15'
  pod 'DZNEmptyDataSet'
  pod 'AZSClient'
  pod 'MaterialShowcase'
  pod 'Hero'

  pod 'TwilioVideo'
  
  #pod 'FirKKebase/Auth'
  #pod 'Firebase/Firestore'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
#  pod 'Firebase/Performance'

#  pod 'FirebasePerformance'
#  pod 'Charts', '~> 3.6.0'
pod 'Charts'

  pod 'DropDown'
#  pod 'FreshchatSDK', '~> 5.4.3'
  pod 'FreshchatSDK'
  pod 'SwiftyStoreKit'
  
  pod 'SurveySparrowSdk', :git => 'https://github.com/surveysparrow/surveysparrow-ios-sdk.git', :tag => '0.3.0'
  pod 'KDCircularProgress'
  pod 'HGCircularSlider'
  
  pod 'razorpay-pod'
  pod 'ImageViewer.swift'
  
  pod 'Apxor-Core', '2.9.91'
  pod 'Apxor-CE', '1.5.2'
  pod 'Apxor-RTA', '1.8.81'
  pod 'Apxor-Survey', '1.3.9'
  pod 'Apxor-WYSIWYG', '1.2.51'
  pod 'Apxor-Push', '1.0.741'
  
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        # Targets that do not support m1 simulator
#        if ['WebEngage'].include? target.name
##          config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
#          config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#        end
#      end
#    end
#  end

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNScreens') || pod.name.eql?('RCTImageLoader') || pod.name.eql?('RNReanimated')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Needed for building for simulator on M1 Macs
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        # config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
  
end


# ServiceExtension Target
target 'MyTatvaNotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    platform :ios, '13.0'
    
    pod 'WebEngageBannerPush'
end

# ContentExtension Target
target 'NotificationViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
  platform :ios, '13.0'
  
  pod 'WebEngageAppEx/ContentExtension'
end
